### ISSUE TITLE
Remote recordings not working on openatv and openhdf

### ISSUE THREAD

**Issue by jrodzar** [openmips/gbremote-client#1]
My setup consists in one GigaBlue Quad Plus acting as a server and one Gigablue IPBox as a client (using the preinstalled GBIPBoxClient on openATV and openHDF). My server can record correctly to /hdd/movie. My IPBox can display all channels from the server without problems, but every time I try to record any channel I get the following error displayed at the server screen: "Write error while recording. Disk full?"
I've tried doing the same thing with openMIPS and it works correctly. Any thoughts?

**Comment by arn354** [comment]
I am not sure if openhdf and openatv included all ipbox e2 changes like on openmips.

**Comment by atvcaptain** [comment]
no infos about the changes need for ipbox

**Comment by arn354** [comment]
https://github.com/openatv/enigma2/commit/354563dfa3b86fe6980e57167f4cc721c7c0d38c
in openatv it should be included.

**Comment by jrodzar** [comment]
Well, I've tried with fresh installations, with both 4.2 and 4.3 versions of openATV, with same results. When the timer is created on the server side, the location is empty, instead of /media/hdd/movie.
